# Generated by Django 5.1.15 on 2026-07-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='challenge',
            new_name='challenges__slug_85cc59_idx',
            old_name='challenges__slug_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='challenge',
            new_name='challenges__challen_fee395_idx',
            old_name='challenges__challen_654321_idx',
        ),
        migrations.RenameIndex(
            model_name='challenge',
            new_name='challenges__difficu_daa6f9_idx',
            old_name='challenges__difficu_789012_idx',
        ),
        migrations.RenameIndex(
            model_name='challengequestion',
            new_name='challenges__challen_a1581f_idx',
            old_name='challenges__challen_567890_idx',
        ),
        migrations.RenameIndex(
            model_name='evidence',
            new_name='challenges__challen_f4e3d7_idx',
            old_name='challenges__challen_345678_idx',
        ),
        migrations.RenameIndex(
            model_name='evidence',
            new_name='challenges__file_fo_04a6f9_idx',
            old_name='challenges__file_fo_901234_idx',
        ),
    ]
