# Generated by Django 5.1.15 on 2026-07-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_event_c_bd949b_idx',
            old_name='events_even_event_c_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_status_5709b6_idx',
            old_name='events_even_status_654321_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_college_1622f2_idx',
            old_name='events_even_college_789012_idx',
        ),
        migrations.RenameIndex(
            model_name='eventquestion',
            new_name='events_even_event_i_eb7431_idx',
            old_name='events_even_event_i_345678_idx',
        ),
    ]
