# Generated by Django 5.1.15 on 2026-07-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_events_even_event_c_123456_idx_events_even_event_c_bd949b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_close',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_publish',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='banner_image',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='banner_image_url',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_close_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_open_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
