# Generated by Django 5.1.15 on 2026-08-03 18:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_auto_close_event_auto_publish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedStudent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_name', models.CharField(db_index=True, max_length=200)),
                ('registered_email', models.EmailField(db_index=True, max_length=254)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_students', to='events.event')),
            ],
            options={
                'verbose_name': 'Approved Student',
                'verbose_name_plural': 'Approved Students',
                'ordering': ['registered_name'],
                'indexes': [models.Index(fields=['event', 'registered_email'], name='events_appr_event_i_c38a7b_idx'), models.Index(fields=['registered_email'], name='events_appr_registe_a2d6e4_idx')],
                'unique_together': {('event', 'registered_email')},
            },
        ),
    ]
