# Generated by Django 5.1.15 on 2026-07-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_participant_progress_and_draft'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='participant',
            new_name='participant_event_i_088c1d_idx',
            old_name='participant_event_i_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='participant',
            new_name='participant_event_i_27e558_idx',
            old_name='participant_event_i_654321_idx',
        ),
        migrations.RenameIndex(
            model_name='participant',
            new_name='participant_score_9be57b_idx',
            old_name='participant_score_789012_idx',
        ),
        migrations.RenameIndex(
            model_name='participantdraftanswer',
            new_name='participant_partici_8c1ef0_idx',
            old_name='partic_draft_p_c_idx',
        ),
        migrations.RenameIndex(
            model_name='participantprogress',
            new_name='participant_partici_3c9752_idx',
            old_name='partic_prog_p_c_idx',
        ),
        migrations.RenameIndex(
            model_name='participantprogress',
            new_name='participant_partici_6de668_idx',
            old_name='partic_prog_p_s_idx',
        ),
    ]
