# Generated by Django 5.1.15 on 2026-08-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0003_rename_participant_event_i_123456_idx_participant_event_i_088c1d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantprogress',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='participantprogress',
            name='draft_answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='participantprogress',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='participantprogress',
            name='max_possible_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='participantprogress',
            name='time_limit_seconds',
            field=models.PositiveIntegerField(blank=True, default=1200),
        ),
        migrations.AlterField(
            model_name='participantprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired')], db_index=True, default='not_started', max_length=20),
        ),
    ]
