# Generated by Django 5.1.15 on 2026-07-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_action__dd3a3c_idx',
            old_name='audit_log_action__idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_timesta_19e18a_idx',
            old_name='audit_log_timesta_idx',
        ),
    ]
