# Generated by Django 5.1.15 on 2026-07-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='question',
            new_name='questions_q_categor_f1803c_idx',
            old_name='questions_q_categor_123456_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='questions_q_difficu_5db314_idx',
            old_name='questions_q_difficu_654321_idx',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='questions_q_status_fca2ef_idx',
            old_name='questions_q_status_789012_idx',
        ),
    ]
