# Generated by Django 5.1.15 on 2026-07-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_token_affdf2_idx',
            old_name='accounts_pa_token_23bb0b_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='accounts_pa_expires_01b447_idx',
            old_name='accounts_pa_expires_6717a0_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_email_74c8d6_idx',
            old_name='accounts_us_email_74c82f_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_role_1fa9a5_idx',
            old_name='accounts_us_role_2c87bf_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='accounts_us_created_4734df_idx',
            old_name='accounts_us_created_5f81cb_idx',
        ),
    ]
