# Generated by Django 5.1.15 on 2026-07-28 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_partici_975045_idx',
            old_name='submissions_part_chal_idx',
        ),
        migrations.RenameIndex(
            model_name='submission',
            new_name='submissions_submitt_f62c88_idx',
            old_name='submissions_sub_at_idx',
        ),
    ]
