/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as CompetitionCompleteRouteImport } from './routes/competition-complete'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as EventRouteImport } from './routes/event'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as ChallengePlayRouteImport } from './routes/challenge.play'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitionCompleteRoute = CompetitionCompleteRouteImport.update({
  id: '/competition-complete',
  path: '/competition-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengePlayRoute = ChallengePlayRouteImport.update({
  id: '/challenge/play',
  path: '/challenge/play',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/challenges': typeof ChallengesRoute
  '/competition-complete': typeof CompetitionCompleteRoute
  '/dashboard': typeof DashboardRoute
  '/event': typeof EventRoute
  '/leaderboard': typeof LeaderboardRoute
  '/review': typeof ReviewRoute
  '/student': typeof StudentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/challenge/play': typeof ChallengePlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/challenges': typeof ChallengesRoute
  '/competition-complete': typeof CompetitionCompleteRoute
  '/dashboard': typeof DashboardRoute
  '/event': typeof EventRoute
  '/leaderboard': typeof LeaderboardRoute
  '/review': typeof ReviewRoute
  '/student': typeof StudentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/challenge/play': typeof ChallengePlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/arena': typeof ArenaRoute
  '/challenges': typeof ChallengesRoute
  '/competition-complete': typeof CompetitionCompleteRoute
  '/dashboard': typeof DashboardRoute
  '/event': typeof EventRoute
  '/leaderboard': typeof LeaderboardRoute
  '/review': typeof ReviewRoute
  '/student': typeof StudentRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/challenge/play': typeof ChallengePlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/arena'
    | '/challenges'
    | '/competition-complete'
    | '/dashboard'
    | '/event'
    | '/leaderboard'
    | '/review'
    | '/student'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/login'
    | '/admin/questions'
    | '/challenge/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/arena'
    | '/challenges'
    | '/competition-complete'
    | '/dashboard'
    | '/event'
    | '/leaderboard'
    | '/review'
    | '/student'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/login'
    | '/admin/questions'
    | '/challenge/play'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/arena'
    | '/challenges'
    | '/competition-complete'
    | '/dashboard'
    | '/event'
    | '/leaderboard'
    | '/review'
    | '/student'
    | '/admin/dashboard'
    | '/admin/events'
    | '/admin/login'
    | '/admin/questions'
    | '/challenge/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArenaRoute: typeof ArenaRoute
  ChallengesRoute: typeof ChallengesRoute
  CompetitionCompleteRoute: typeof CompetitionCompleteRoute
  DashboardRoute: typeof DashboardRoute
  EventRoute: typeof EventRoute
  LeaderboardRoute: typeof LeaderboardRoute
  ReviewRoute: typeof ReviewRoute
  StudentRoute: typeof StudentRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  ChallengePlayRoute: typeof ChallengePlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competition-complete': {
      id: '/competition-complete'
      path: '/competition-complete'
      fullPath: '/competition-complete'
      preLoaderRoute: typeof CompetitionCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/play': {
      id: '/challenge/play'
      path: '/challenge/play'
      fullPath: '/challenge/play'
      preLoaderRoute: typeof ChallengePlayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArenaRoute: ArenaRoute,
  ChallengesRoute: ChallengesRoute,
  CompetitionCompleteRoute: CompetitionCompleteRoute,
  DashboardRoute: DashboardRoute,
  EventRoute: EventRoute,
  LeaderboardRoute: LeaderboardRoute,
  ReviewRoute: ReviewRoute,
  StudentRoute: StudentRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  ChallengePlayRoute: ChallengePlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
